/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  L1NovaApprovalEscrow,
  L1NovaApprovalEscrowInterface,
} from "../L1NovaApprovalEscrow";

const _abi = [
  {
    inputs: [],
    name: "ESCROW_ADMIN",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
    ],
    name: "transferApprovedToken",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x60a06040523360601b60805234801561001757600080fd5b5060805160601c6103456100396000398060cd528061031652506103456000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c8063178c47751461003b5780634719c36114610098575b600080fd5b6100846004803603608081101561005157600080fd5b5073ffffffffffffffffffffffffffffffffffffffff8135811691602081013591604082013581169160600135166100c9565b604080519115158252519081900360200190f35b6100a0610314565b6040805173ffffffffffffffffffffffffffffffffffffffff9092168252519081900360200190f35b60007f000000000000000000000000000000000000000000000000000000000000000073ffffffffffffffffffffffffffffffffffffffff16331461016f57604080517f08c379a000000000000000000000000000000000000000000000000000000000815260206004820152600c60248201527f554e415554484f52495a45440000000000000000000000000000000000000000604482015290519081900360640190fd5b6040805173ffffffffffffffffffffffffffffffffffffffff85811660248301528481166044830152606480830188905283518084039091018152608490920183526020820180517bffffffffffffffffffffffffffffffffffffffffffffffffffffffff167f23b872dd00000000000000000000000000000000000000000000000000000000178152925182516000948594938b169392918291908083835b6020831061024c57805182527fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe0909201916020918201910161020f565b6001836020036101000a0380198251168184511680821785525050505050509050019150506000604051808303816000865af19150503d80600081146102ae576040519150601f19603f3d011682016040523d82523d6000602084013e6102b3565b606091505b5091509150816102c85760009250505061030c565b805115610305578051602014156102fa578080602001905160208110156102ee57600080fd5b5051925061030c915050565b60009250505061030c565b6001925050505b949350505050565b7f00000000000000000000000000000000000000000000000000000000000000008156fea164736f6c6343000706000a";

export class L1NovaApprovalEscrow__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<L1NovaApprovalEscrow> {
    return super.deploy(overrides || {}) as Promise<L1NovaApprovalEscrow>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): L1NovaApprovalEscrow {
    return super.attach(address) as L1NovaApprovalEscrow;
  }
  connect(signer: Signer): L1NovaApprovalEscrow__factory {
    return super.connect(signer) as L1NovaApprovalEscrow__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): L1NovaApprovalEscrowInterface {
    return new utils.Interface(_abi) as L1NovaApprovalEscrowInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): L1NovaApprovalEscrow {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as L1NovaApprovalEscrow;
  }
}
