/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { MockAuthority, MockAuthorityInterface } from "../MockAuthority";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    name: "canCall",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060ba8061001f6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063b700961314602d575b600080fd5b609060048036036060811015604157600080fd5b50803573ffffffffffffffffffffffffffffffffffffffff90811691602081013590911690604001357fffffffff000000000000000000000000000000000000000000000000000000001660a4565b604080519115158252519081900360200190f35b6001939250505056fea164736f6c6343000706000a";

export class MockAuthority__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<MockAuthority> {
    return super.deploy(overrides || {}) as Promise<MockAuthority>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): MockAuthority {
    return super.attach(address) as MockAuthority;
  }
  connect(signer: Signer): MockAuthority__factory {
    return super.connect(signer) as MockAuthority__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockAuthorityInterface {
    return new utils.Interface(_abi) as MockAuthorityInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MockAuthority {
    return new Contract(address, _abi, signerOrProvider) as MockAuthority;
  }
}
