/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  NoReturnValueERC20,
  NoReturnValueERC20Interface,
} from "../NoReturnValueERC20";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "Transfer",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "a1",
        type: "address",
      },
      {
        internalType: "address",
        name: "a2",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "u1",
        type: "uint256",
      },
    ],
    name: "transferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b5060e68061001e6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c806323b872dd14602d575b600080fd5b606d60048036036060811015604157600080fd5b5073ffffffffffffffffffffffffffffffffffffffff813581169160208101359091169060400135606f565b005b8173ffffffffffffffffffffffffffffffffffffffff168373ffffffffffffffffffffffffffffffffffffffff167fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef836040518082815260200191505060405180910390a350505056fea164736f6c6343000706000a";

export class NoReturnValueERC20__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<NoReturnValueERC20> {
    return super.deploy(overrides || {}) as Promise<NoReturnValueERC20>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): NoReturnValueERC20 {
    return super.attach(address) as NoReturnValueERC20;
  }
  connect(signer: Signer): NoReturnValueERC20__factory {
    return super.connect(signer) as NoReturnValueERC20__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): NoReturnValueERC20Interface {
    return new utils.Interface(_abi) as NoReturnValueERC20Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): NoReturnValueERC20 {
    return new Contract(address, _abi, signerOrProvider) as NoReturnValueERC20;
  }
}
