/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  NovaExecHashLib,
  NovaExecHashLibInterface,
} from "../NovaExecHashLib";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes8",
        name: "c__d28d5623",
        type: "bytes8",
      },
    ],
    name: "c_d28d5623",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes8",
        name: "c__d28d5623",
        type: "bytes8",
      },
    ],
    name: "c_falsed28d5623",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes8",
        name: "c__d28d5623",
        type: "bytes8",
      },
    ],
    name: "c_trued28d5623",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x610179610026600b82828239805160001a60731461001957fe5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361061004b5760003560e01c806307c1747e146100505780635e31345f146100af578063c0690baa1461010e575b600080fd5b6100976004803603602081101561006657600080fd5b81019080803577ffffffffffffffffffffffffffffffffffffffffffffffff19169060200190929190505050610157565b60405180821515815260200191505060405180910390f35b6100f6600480360360208110156100c557600080fd5b81019080803577ffffffffffffffffffffffffffffffffffffffffffffffff19169060200190929190505050610162565b60405180821515815260200191505060405180910390f35b6101556004803603602081101561012457600080fd5b81019080803577ffffffffffffffffffffffffffffffffffffffffffffffff19169060200190929190505050610169565b005b600060019050919050565b6000919050565b5056fea164736f6c6343000706000a";

export class NovaExecHashLib__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<NovaExecHashLib> {
    return super.deploy(overrides || {}) as Promise<NovaExecHashLib>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): NovaExecHashLib {
    return super.attach(address) as NovaExecHashLib;
  }
  connect(signer: Signer): NovaExecHashLib__factory {
    return super.connect(signer) as NovaExecHashLib__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): NovaExecHashLibInterface {
    return new utils.Interface(_abi) as NovaExecHashLibInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): NovaExecHashLib {
    return new Contract(address, _abi, signerOrProvider) as NovaExecHashLib;
  }
}
