/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface L1NovaExecutionManagerInterface extends ethers.utils.Interface {
  functions: {
    "CROSS_DOMAIN_MESSENGER()": FunctionFragment;
    "DEFAULT_EXECHASH()": FunctionFragment;
    "HARD_REVERT_HASH()": FunctionFragment;
    "HARD_REVERT_TEXT()": FunctionFragment;
    "L1_NOVA_APPROVAL_ESCROW()": FunctionFragment;
    "L2_NOVA_REGISTRY_ADDRESS()": FunctionFragment;
    "authority()": FunctionFragment;
    "currentExecHash()": FunctionFragment;
    "currentRelayer()": FunctionFragment;
    "currentlyExecutingStrategy()": FunctionFragment;
    "exec(uint256,address,bytes,uint256,address,uint256)": FunctionFragment;
    "gasConfig()": FunctionFragment;
    "getStrategyRiskLevel(address)": FunctionFragment;
    "hardRevert()": FunctionFragment;
    "owner()": FunctionFragment;
    "registerSelfAsStrategy(uint8)": FunctionFragment;
    "setAuthority(address)": FunctionFragment;
    "setOwner(address)": FunctionFragment;
    "transferFromRelayer(address,uint256)": FunctionFragment;
    "updateGasConfig(tuple)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "CROSS_DOMAIN_MESSENGER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_EXECHASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "HARD_REVERT_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "HARD_REVERT_TEXT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "L1_NOVA_APPROVAL_ESCROW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "L2_NOVA_REGISTRY_ADDRESS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "authority", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "currentExecHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentRelayer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentlyExecutingStrategy",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "exec",
    values: [
      BigNumberish,
      string,
      BytesLike,
      BigNumberish,
      string,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "gasConfig", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getStrategyRiskLevel",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "hardRevert",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerSelfAsStrategy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthority",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "setOwner", values: [string]): string;
  encodeFunctionData(
    functionFragment: "transferFromRelayer",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateGasConfig",
    values: [
      {
        calldataByteGasEstimate: BigNumberish;
        missingGasEstimate: BigNumberish;
        strategyCallGasBuffer: BigNumberish;
        execCompletedMessageGasLimit: BigNumberish;
      }
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "CROSS_DOMAIN_MESSENGER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_EXECHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "HARD_REVERT_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "HARD_REVERT_TEXT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "L1_NOVA_APPROVAL_ESCROW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "L2_NOVA_REGISTRY_ADDRESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "authority", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "currentExecHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentRelayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentlyExecutingStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "exec", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gasConfig", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getStrategyRiskLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hardRevert", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerSelfAsStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFromRelayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateGasConfig",
    data: BytesLike
  ): Result;

  events: {
    "AuthorityUpdated(address)": EventFragment;
    "Exec(bytes32,address,bool,uint256)": EventFragment;
    "GasConfigUpdated(tuple)": EventFragment;
    "OwnerUpdated(address)": EventFragment;
    "StrategyRegistered(uint8)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AuthorityUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Exec"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GasConfigUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnerUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StrategyRegistered"): EventFragment;
}

export class L1NovaExecutionManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: L1NovaExecutionManagerInterface;

  functions: {
    CROSS_DOMAIN_MESSENGER(overrides?: CallOverrides): Promise<[string]>;

    DEFAULT_EXECHASH(overrides?: CallOverrides): Promise<[string]>;

    HARD_REVERT_HASH(overrides?: CallOverrides): Promise<[string]>;

    HARD_REVERT_TEXT(overrides?: CallOverrides): Promise<[string]>;

    L1_NOVA_APPROVAL_ESCROW(overrides?: CallOverrides): Promise<[string]>;

    L2_NOVA_REGISTRY_ADDRESS(overrides?: CallOverrides): Promise<[string]>;

    authority(overrides?: CallOverrides): Promise<[string]>;

    currentExecHash(overrides?: CallOverrides): Promise<[string]>;

    currentRelayer(overrides?: CallOverrides): Promise<[string]>;

    currentlyExecutingStrategy(overrides?: CallOverrides): Promise<[string]>;

    exec(
      nonce: BigNumberish,
      strategy: string,
      l1Calldata: BytesLike,
      gasLimit: BigNumberish,
      l2Recipient: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    gasConfig(
      overrides?: CallOverrides
    ): Promise<
      [number, BigNumber, BigNumber, number] & {
        calldataByteGasEstimate: number;
        missingGasEstimate: BigNumber;
        strategyCallGasBuffer: BigNumber;
        execCompletedMessageGasLimit: number;
      }
    >;

    getStrategyRiskLevel(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[number]>;

    hardRevert(overrides?: CallOverrides): Promise<[void]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    registerSelfAsStrategy(
      strategyRiskLevel: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setAuthority(
      newAuthority: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setOwner(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferFromRelayer(
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateGasConfig(
      newGasConfig: {
        calldataByteGasEstimate: BigNumberish;
        missingGasEstimate: BigNumberish;
        strategyCallGasBuffer: BigNumberish;
        execCompletedMessageGasLimit: BigNumberish;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  CROSS_DOMAIN_MESSENGER(overrides?: CallOverrides): Promise<string>;

  DEFAULT_EXECHASH(overrides?: CallOverrides): Promise<string>;

  HARD_REVERT_HASH(overrides?: CallOverrides): Promise<string>;

  HARD_REVERT_TEXT(overrides?: CallOverrides): Promise<string>;

  L1_NOVA_APPROVAL_ESCROW(overrides?: CallOverrides): Promise<string>;

  L2_NOVA_REGISTRY_ADDRESS(overrides?: CallOverrides): Promise<string>;

  authority(overrides?: CallOverrides): Promise<string>;

  currentExecHash(overrides?: CallOverrides): Promise<string>;

  currentRelayer(overrides?: CallOverrides): Promise<string>;

  currentlyExecutingStrategy(overrides?: CallOverrides): Promise<string>;

  exec(
    nonce: BigNumberish,
    strategy: string,
    l1Calldata: BytesLike,
    gasLimit: BigNumberish,
    l2Recipient: string,
    deadline: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  gasConfig(
    overrides?: CallOverrides
  ): Promise<
    [number, BigNumber, BigNumber, number] & {
      calldataByteGasEstimate: number;
      missingGasEstimate: BigNumber;
      strategyCallGasBuffer: BigNumber;
      execCompletedMessageGasLimit: number;
    }
  >;

  getStrategyRiskLevel(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<number>;

  hardRevert(overrides?: CallOverrides): Promise<void>;

  owner(overrides?: CallOverrides): Promise<string>;

  registerSelfAsStrategy(
    strategyRiskLevel: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setAuthority(
    newAuthority: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setOwner(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferFromRelayer(
    token: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateGasConfig(
    newGasConfig: {
      calldataByteGasEstimate: BigNumberish;
      missingGasEstimate: BigNumberish;
      strategyCallGasBuffer: BigNumberish;
      execCompletedMessageGasLimit: BigNumberish;
    },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    CROSS_DOMAIN_MESSENGER(overrides?: CallOverrides): Promise<string>;

    DEFAULT_EXECHASH(overrides?: CallOverrides): Promise<string>;

    HARD_REVERT_HASH(overrides?: CallOverrides): Promise<string>;

    HARD_REVERT_TEXT(overrides?: CallOverrides): Promise<string>;

    L1_NOVA_APPROVAL_ESCROW(overrides?: CallOverrides): Promise<string>;

    L2_NOVA_REGISTRY_ADDRESS(overrides?: CallOverrides): Promise<string>;

    authority(overrides?: CallOverrides): Promise<string>;

    currentExecHash(overrides?: CallOverrides): Promise<string>;

    currentRelayer(overrides?: CallOverrides): Promise<string>;

    currentlyExecutingStrategy(overrides?: CallOverrides): Promise<string>;

    exec(
      nonce: BigNumberish,
      strategy: string,
      l1Calldata: BytesLike,
      gasLimit: BigNumberish,
      l2Recipient: string,
      deadline: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    gasConfig(
      overrides?: CallOverrides
    ): Promise<
      [number, BigNumber, BigNumber, number] & {
        calldataByteGasEstimate: number;
        missingGasEstimate: BigNumber;
        strategyCallGasBuffer: BigNumber;
        execCompletedMessageGasLimit: number;
      }
    >;

    getStrategyRiskLevel(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<number>;

    hardRevert(overrides?: CallOverrides): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    registerSelfAsStrategy(
      strategyRiskLevel: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setAuthority(
      newAuthority: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setOwner(newOwner: string, overrides?: CallOverrides): Promise<void>;

    transferFromRelayer(
      token: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateGasConfig(
      newGasConfig: {
        calldataByteGasEstimate: BigNumberish;
        missingGasEstimate: BigNumberish;
        strategyCallGasBuffer: BigNumberish;
        execCompletedMessageGasLimit: BigNumberish;
      },
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    AuthorityUpdated(
      authority?: string | null
    ): TypedEventFilter<[string], { authority: string }>;

    Exec(
      execHash?: BytesLike | null,
      relayer?: null,
      reverted?: null,
      gasUsed?: null
    ): TypedEventFilter<
      [string, string, boolean, BigNumber],
      {
        execHash: string;
        relayer: string;
        reverted: boolean;
        gasUsed: BigNumber;
      }
    >;

    GasConfigUpdated(
      newGasConfig?: null
    ): TypedEventFilter<
      [
        [number, BigNumber, BigNumber, number] & {
          calldataByteGasEstimate: number;
          missingGasEstimate: BigNumber;
          strategyCallGasBuffer: BigNumber;
          execCompletedMessageGasLimit: number;
        }
      ],
      {
        newGasConfig: [number, BigNumber, BigNumber, number] & {
          calldataByteGasEstimate: number;
          missingGasEstimate: BigNumber;
          strategyCallGasBuffer: BigNumber;
          execCompletedMessageGasLimit: number;
        };
      }
    >;

    OwnerUpdated(
      owner?: string | null
    ): TypedEventFilter<[string], { owner: string }>;

    StrategyRegistered(
      strategyRiskLevel?: null
    ): TypedEventFilter<[number], { strategyRiskLevel: number }>;
  };

  estimateGas: {
    CROSS_DOMAIN_MESSENGER(overrides?: CallOverrides): Promise<BigNumber>;

    DEFAULT_EXECHASH(overrides?: CallOverrides): Promise<BigNumber>;

    HARD_REVERT_HASH(overrides?: CallOverrides): Promise<BigNumber>;

    HARD_REVERT_TEXT(overrides?: CallOverrides): Promise<BigNumber>;

    L1_NOVA_APPROVAL_ESCROW(overrides?: CallOverrides): Promise<BigNumber>;

    L2_NOVA_REGISTRY_ADDRESS(overrides?: CallOverrides): Promise<BigNumber>;

    authority(overrides?: CallOverrides): Promise<BigNumber>;

    currentExecHash(overrides?: CallOverrides): Promise<BigNumber>;

    currentRelayer(overrides?: CallOverrides): Promise<BigNumber>;

    currentlyExecutingStrategy(overrides?: CallOverrides): Promise<BigNumber>;

    exec(
      nonce: BigNumberish,
      strategy: string,
      l1Calldata: BytesLike,
      gasLimit: BigNumberish,
      l2Recipient: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    gasConfig(overrides?: CallOverrides): Promise<BigNumber>;

    getStrategyRiskLevel(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hardRevert(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    registerSelfAsStrategy(
      strategyRiskLevel: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setAuthority(
      newAuthority: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setOwner(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferFromRelayer(
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateGasConfig(
      newGasConfig: {
        calldataByteGasEstimate: BigNumberish;
        missingGasEstimate: BigNumberish;
        strategyCallGasBuffer: BigNumberish;
        execCompletedMessageGasLimit: BigNumberish;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    CROSS_DOMAIN_MESSENGER(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    DEFAULT_EXECHASH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    HARD_REVERT_HASH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    HARD_REVERT_TEXT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    L1_NOVA_APPROVAL_ESCROW(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    L2_NOVA_REGISTRY_ADDRESS(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    authority(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    currentExecHash(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    currentRelayer(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    currentlyExecutingStrategy(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    exec(
      nonce: BigNumberish,
      strategy: string,
      l1Calldata: BytesLike,
      gasLimit: BigNumberish,
      l2Recipient: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    gasConfig(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getStrategyRiskLevel(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hardRevert(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    registerSelfAsStrategy(
      strategyRiskLevel: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setAuthority(
      newAuthority: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setOwner(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferFromRelayer(
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateGasConfig(
      newGasConfig: {
        calldataByteGasEstimate: BigNumberish;
        missingGasEstimate: BigNumberish;
        strategyCallGasBuffer: BigNumberish;
        execCompletedMessageGasLimit: BigNumberish;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
