/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface L1NovaApprovalEscrowInterface extends ethers.utils.Interface {
  functions: {
    "ESCROW_ADMIN()": FunctionFragment;
    "transferApprovedToken(address,uint256,address,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "ESCROW_ADMIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferApprovedToken",
    values: [string, BigNumberish, string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "ESCROW_ADMIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferApprovedToken",
    data: BytesLike
  ): Result;

  events: {};
}

export class L1NovaApprovalEscrow extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: L1NovaApprovalEscrowInterface;

  functions: {
    ESCROW_ADMIN(overrides?: CallOverrides): Promise<[string]>;

    transferApprovedToken(
      token: string,
      amount: BigNumberish,
      sender: string,
      recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  ESCROW_ADMIN(overrides?: CallOverrides): Promise<string>;

  transferApprovedToken(
    token: string,
    amount: BigNumberish,
    sender: string,
    recipient: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    ESCROW_ADMIN(overrides?: CallOverrides): Promise<string>;

    transferApprovedToken(
      token: string,
      amount: BigNumberish,
      sender: string,
      recipient: string,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    ESCROW_ADMIN(overrides?: CallOverrides): Promise<BigNumber>;

    transferApprovedToken(
      token: string,
      amount: BigNumberish,
      sender: string,
      recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    ESCROW_ADMIN(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferApprovedToken(
      token: string,
      amount: BigNumberish,
      sender: string,
      recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
