/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface NovaExecHashLibInterface extends ethers.utils.Interface {
  functions: {
    "c_d28d5623(bytes8)": FunctionFragment;
    "c_falsed28d5623(bytes8)": FunctionFragment;
    "c_trued28d5623(bytes8)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "c_d28d5623",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "c_falsed28d5623",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "c_trued28d5623",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "c_d28d5623", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "c_falsed28d5623",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "c_trued28d5623",
    data: BytesLike
  ): Result;

  events: {};
}

export class NovaExecHashLib extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: NovaExecHashLibInterface;

  functions: {
    c_d28d5623(
      c__d28d5623: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;

    c_falsed28d5623(
      c__d28d5623: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    c_trued28d5623(
      c__d28d5623: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  c_d28d5623(c__d28d5623: BytesLike, overrides?: CallOverrides): Promise<void>;

  c_falsed28d5623(
    c__d28d5623: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  c_trued28d5623(
    c__d28d5623: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    c_d28d5623(
      c__d28d5623: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    c_falsed28d5623(
      c__d28d5623: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    c_trued28d5623(
      c__d28d5623: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    c_d28d5623(
      c__d28d5623: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    c_falsed28d5623(
      c__d28d5623: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    c_trued28d5623(
      c__d28d5623: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    c_d28d5623(
      c__d28d5623: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    c_falsed28d5623(
      c__d28d5623: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    c_trued28d5623(
      c__d28d5623: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
